### Get All Customers
GET http://localhost:8080/v1/customer?phoneNumber=62&name=dav HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVdWlkIjoiMjQ0NDA3YWMtZmYxNS00OGJhLWFjNzEtYjBmMDczMTIzOWFjIiwiaXNzIjoiRW5pUWlsbyIsInN1YiI6ImpvaG4gZG9lIiwiZXhwIjoxNzE1NTE0MTc5LCJpYXQiOjE3MTU0ODUzNzksImp0aSI6IjI0NDQwN2FjLWZmMTUtNDhiYS1hYzcxLWIwZjA3MzEyMzlhYyJ9._3ZcBfI3N33i9t--p6S7wXfQWhB1nUdKgATYgXZPpPs